// <auto-generated />
using AuthService.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuthService.Infrastructure.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20251115003333_CreateTables")]
    partial class CreateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthService.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "administrador@teste.com",
                            Name = "Administrador",
                            PasswordHash = "+PZDg/QC6WiGmD4PsVox4J93XsQpVgwhf9p7kFoWpZM=",
                            PasswordSalt = "lxDM6u0i1QzkH9qjLcbddQncvod+GAUnq3P0/SRbDgo2g/A/f5aQxsebHJy0WO5zVWYdHf9iH/NUcd9Ekfo0Xg==",
                            Role = 2
                        },
                        new
                        {
                            Id = 2L,
                            Email = "client@teste.com",
                            Name = "Client",
                            PasswordHash = "rib/htc/z3A7WTpkyiq+WS6r9d6UNeKrK9uxsMHNmKc=",
                            PasswordSalt = "DIWblV8sddpnht/d1qPcIw3giLSrhDT5qbrPfGoML9J7y7EnrMxB96uLqGVLIAmEIw+vutavTmgafLRq4CI9bg==",
                            Role = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
