// <auto-generated />
using AuthService.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuthService.Infrastructure.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthService.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "administrador@teste.com",
                            Name = "Administrador",
                            PasswordHash = "qHdYgya3+jXN3EvJ4qV+uBYy2IR5wEZkFZnbJ3XqY3c=",
                            PasswordSalt = "z6BA73RFdQTaMqphM4LL0D9ompdVsRzvON5afnwdWHzZYTUcTZPIlOZSRFX28C7inCt8JnKFVZqknLw3J8RxHA==",
                            Role = 2
                        },
                        new
                        {
                            Id = 2L,
                            Email = "client@teste.com",
                            Name = "Client",
                            PasswordHash = "wQrdevPOCOalGsrU5gQ6XDpsrkKPWr/Pvx48SIlV0e0=",
                            PasswordSalt = "P3vB6UENYsruyHs9OZIv47SleIhms3tY2DA9fkCfy129fDTuxvTrYLcBsV3di7uttM9L8J+G905AhlAqB/5ibA==",
                            Role = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
